### ISSUE TITLE
`defineTask('init', ...);` in README.md should be task('init', ...)

### ISSUE THREAD

**Issue by zoechi** [NicholasTuck/grinder_automated_test_task#2]
I'm just starting to play with grinder, but I didn't find a `defineTask` anywhere so I guess this should be `task`

**Comment by NicholasTuck** [comment]
Thanks Gunter.  It's been a while since I have updated versions so hopefully just a mismatch on a version update.  I will take a look soon.

**Comment by zoechi** [comment]
They are doing a lot of rework currently.
